languageCode = "en-us"
title = "Justin Downing"
author = "Justin Downing"
baseurl = "http://justin.downing.us"
theme = "cocoa-eh"

builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Justin Downing"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "assets/logo.png"
faviconfile = "assets/logo.png"
highlightjs = true
lang = "en"
github = "https://github.com/justindowning"
#email = "you@example.com"
linkedin = "https://linkedin.com/in/justindowning"
twitter = "https://twitter.com/_jdowning"
spotify = "https://open.spotify.com/user/itguy12"
